version: 2
updates:
# Disabling as going to pin for non OSS use
#  - package-ecosystem: "cargo"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      day: "monday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
