name: Rust CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust Cargo CI on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Installing libdbus
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev pkg-config

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Cargo release + all feature build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Show development + release build sizes
        run: |
          ls -lh target/debug/
          ls -lh target/release/
